@startuml sigma
abstract class Vehicle
abstract class PassengerTransport
abstract class Car
class FuelCar
class ElectricCar
class Bicycle
abstract class MaterialTransport
class FuelTruck
class ElectricTruck

abstract class FuelingStation
class FuelStation
class ChargingStation

enum RoadType {
    HIGHWAY
    CITY
    BACKROAD
    OFFROAD
}

PassengerTransport <|-- Vehicle
Car <|-- PassengerTransport
FuelCar <|-- Car
ElectricCar <|-- Car
MaterialTransport <|-- Vehicle
FuelTruck <|-- MaterialTransport
ElectricTruck <|-- MaterialTransport
Bicycle <|-- PassengerTransport

FuelStation <|-- FuelingStation
ChargingStation <|-- FuelingStation

Vehicle --o RoadType : drives on
Vehicle --o FuelingStation : refuels at
ElectricCar --o ChargingStation : recharges at
FuelCar --o FuelStation : refuels at
ElectricTruck --o ChargingStation : recharges at
FuelTruck --o FuelStation : refuels at

@enduml